#include "loc/strings.h"
#define WIN32_LEAN_AND_MEAN
#include <windows.h>

static const wchar_t *en[STR_COUNT] = {
    L"Next break in %d:%02d",
    L"Pause",
    L"Take a break now",
    L"Skip next break",
    L"Settings…",
    L"Launch at login",
    L"Quit",
    L"Runs in the tray, no window will open. Click the icon for the menu.",
    L"Resume",
    L"Paused",
    L"Break ends in %d s",
    L"Break every",
    L"%d min",
    L"New timer…",
    L"focus 3 hours",
    L"Look at something 20 feet away",
    L"Skip",
    L"Rest your eyes",
    L"Skip break",
    L"Lock screen",
    L"Press Esc twice to skip the break",
    L"Waiting — you're in a call",
    L"Waiting — fullscreen app",
    L"Waiting — focus app",
    L"Waiting — you look busy",

    L"Breaks",
    L"Notifications",
    L"Sounds",
    L"Schedule",
    L"Shortcuts",
    L"About",

    L"Break every",
    L"Break length",
    L"Smart pause",
    L"Hold the break while you're busy",
    L"Fullscreen apps and games",
    L"Films, games, anything running fullscreen",
    L"Calls and meetings",
    L"Detected while the mic or camera is live",
    L"Focus apps",
    L"Apps you never want interrupted",
    L"Wait after you're free",
    L"Never hold longer than",
    L"So a stuck app can't cancel your breaks",
    L"Count time away as a break",
    L"Step away this long and the timer resets",

    L"Style",
    L"How a break announces itself",
    L"Position",
    L"Where the notification appears",
    L"Fullscreen overlay",
    L"Notification",
    L"Centred popup",
    L"Follow the cursor",
    L"Top left",
    L"Top centre",
    L"Top right",
    L"Bottom left",
    L"Bottom centre",
    L"Bottom right",
    L"Centre",

    L"Play sounds",
    L"Volume",
    L"When a break starts",
    L"When a break ends",
    L"Heads-up sound",
    L"Heads-up timing",
    L"Plays this long before a break",
    L"None",
    L"Chime",
    L"Soft",
    L"Tick",
    L"Bell",
    L"Drop",
    L"Choose a file…",

    L"Only during work hours",
    L"Outside these hours the timer sleeps",
    L"From",
    L"Until",
    L"Days",
    L"Launch at login",

    L"Take a break now",
    L"Skip this break",
    L"Pause and resume",
    L"Click a shortcut, then press the keys",
    L"Press keys…",
    L"Not set",

    L"Eye breaks that stay out of your way.",
    L"Raw Win32, no dependencies, one small exe.",

    L"%d min",
    L"%d sec",
    L"Off",
    L"%d h",
    L"MTWTFSS",
    L"settings",
    L"Already running. Look for the sloth in your tray.",
    L"Custom…",
};

static const wchar_t *tr[STR_COUNT] = {
    L"Sonraki molaya %d:%02d",
    L"Duraklat",
    L"Şimdi mola ver",
    L"Sonraki molayı atla",
    L"Ayarlar…",
    L"Açılışta başlat",
    L"Çıkış Yap",
    L"Tepside çalışır, pencere açılmaz. Menü için simgeye tıkla.",
    L"Devam et",
    L"Duraklatıldı",
    L"Molanın bitmesine %d sn",
    L"Mola sıklığı",
    L"%d dk",
    L"Yeni sayaç…",
    L"odak 3 saat",
    L"6 metre uzaktaki bir şeye bak",
    L"Atla",
    L"Gözlerini dinlendir",
    L"Molayı atla",
    L"Ekranı kilitle",
    L"Molayı atlamak için iki kez Esc'ye bas",
    L"Bekliyor — görüşmedesin",
    L"Bekliyor — tam ekran uygulama",
    L"Bekliyor — odak uygulaması",
    L"Bekliyor — meşgul görünüyorsun",

    L"Molalar",
    L"Bildirimler",
    L"Sesler",
    L"Program",
    L"Kısayollar",
    L"Hakkında",

    L"Mola sıklığı",
    L"Mola süresi",
    L"Akıllı duraklatma",
    L"Meşgulken molayı beklet",
    L"Tam ekran uygulamalar ve oyunlar",
    L"Film, oyun, tam ekran çalışan her şey",
    L"Görüşmeler ve toplantılar",
    L"Mikrofon veya kamera açıkken algılanır",
    L"Odak uygulamaları",
    L"Asla bölünmek istemediğin uygulamalar",
    L"Boşa çıkınca bekleme",
    L"En fazla şu kadar beklet",
    L"Takılan bir uygulama molanı iptal etmesin",
    L"Uzakta geçen süreyi mola say",
    L"Bu kadar uzaklaşınca sayaç sıfırlanır",

    L"Biçim",
    L"Mola kendini nasıl duyursun",
    L"Konum",
    L"Bildirim nerede görünsün",
    L"Tam ekran kaplama",
    L"Bildirim",
    L"Ortada pencere",
    L"İmleci takip et",
    L"Sol üst",
    L"Üst orta",
    L"Sağ üst",
    L"Sol alt",
    L"Alt orta",
    L"Sağ alt",
    L"Orta",

    L"Sesleri çal",
    L"Ses düzeyi",
    L"Mola başlarken",
    L"Mola biterken",
    L"Ön uyarı sesi",
    L"Ön uyarı zamanı",
    L"Moladan bu kadar önce çalar",
    L"Yok",
    L"Çıngırak",
    L"Yumuşak",
    L"Tik",
    L"Zil",
    L"Damla",
    L"Dosya seç…",

    L"Yalnızca çalışma saatlerinde",
    L"Bu saatlerin dışında sayaç uyur",
    L"Başlangıç",
    L"Bitiş",
    L"Günler",
    L"Açılışta başlat",

    L"Şimdi mola ver",
    L"Bu molayı atla",
    L"Duraklat ve devam et",
    L"Bir kısayola tıkla, sonra tuşlara bas",
    L"Tuşlara bas…",
    L"Atanmadı",

    L"Gözlerini yormayan mola hatırlatıcısı.",
    L"Saf Win32, bağımlılık yok, tek küçük exe.",

    L"%d dk",
    L"%d sn",
    L"Kapalı",
    L"%d sa",
    L"PSÇPCCP",
    L"Ayarlar",
    L"Zaten çalışıyor. Tepsideki tembel hayvana bak.",
    L"Özel…",
};

const wchar_t *str(int id)
{
    static const wchar_t **tbl;
    if (!tbl)
        tbl = PRIMARYLANGID(GetUserDefaultUILanguage()) == LANG_TURKISH ? tr : en;
    return tbl[id];
}
